version: "3.7"
services:
  app:
    image: elixir:1.10
    container_name: "${COMPOSE_PROJECT_NAME}app"
    volumes:
        - ./:/var/www/application/
    working_dir: "/var/www/application/"
    expose:
        - "4000"
    tty: true

  nginx:
    image: nginx:1.17
    container_name: "${COMPOSE_PROJECT_NAME}nginx"
    ports:
      - "80:80"

  postgres:
    image: postgres:9.5
    container_name: "${COMPOSE_PROJECT_NAME}postgres"
    volumes:
      - ./postgres:/var/lib/postgres
    environment:
      - POSTGRES_DB=your_db
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_secret
    ports:
      - "5432:5432"
#update on docker compose